### ISSUE TITLE
Is this project really Open Source?

### ISSUE THREAD

**Issue by julianxhokaxhiu** [BrainStormDevel/verysimplecms#2]
Hi,

why are you using IonCube loader if you're publishing this on Github? See https://github.com/BrainStormDevel/verysimplecms/blob/master/main.php

Best Regards,
Julian

**Comment by BrainStormDevel** [comment]
I published this first beta release encrypted to seen how many people are really interested in testing my product for the features and not for the code elegance.

**Comment by garak** [comment]
There is no license, so it's not really Open Source

**Comment by BrainStormDevel** [comment]
The first release was intended for commercial use only (before I push the code here).
Next release I will remove the license check.
