### ISSUE TITLE
Install dependencies via Composer

### ISSUE THREAD

**Issue by julianxhokaxhiu** [BrainStormDevel/verysimplecms#3]
Hi,

looking at the include folder, makes this project feel old even if it's in its very own fresh start.

Therefore, I highly suggest to use Composer as a Dependency manager.

Best regards,
Julian

**Comment by BrainStormDevel** [comment]
Thanks for the suggestion, I will consider to implement a Dependancy Manager in future releases.

**Comment by drAlberT** [comment]
You should not have to **implement**, but simply use it. Keep you DRY guy ;)

**Comment by garak** [comment]
No Maria, I go out

**Comment by BrainStormDevel** [comment]
Please, use this platform for comment on the code and suggest issue, bug fix or new features. Haters, Jokers and kiddies has already enough useless space on the internet.
Thanks.

**Comment by drAlberT** [comment]
I'm **not** joking guy
